import { Shield, Fingerprint, QrCode, Hash, Code2, Braces, Type, Palette, Globe, Wifi, Percent, Calendar, Receipt, Clock, Link, CaseSensitive, Binary, Dices, Sparkles, Music, Piano, TrendingUp, Timer, Shuffle, Gift, Frame, Lock, Text, CalendarDays, CalendarClock, FileCode, ArrowRightLeft, RefreshCw, CircleDot, Ruler, Calculator, Image, Sun, Signal, ListOrdered, HeartPulse, Brain, Terminal, ScanLine, FileCheck, FileText, type LucideIcon } from 'lucide-react';

export const toolIcons: Record<string, LucideIcon> = {
  Shield,
  Fingerprint,
  QrCode,
  Hash,
  Code: Code2,
  Brackets: Braces,
  Type,
  Palette,
  Globe,
  Wifi,
  Percent,
  Calendar,
  Receipt,
  Clock,
  Link,
  CaseSensitive,
  Binary,
  Dices,
  Sparkles,
  Music,
  Piano,
  TrendingUp,
  Timer,
  Shuffle,
  Gift,
  Frame,
  Lock,
  Text,
  CalendarDays,
  CalendarClock,
  FileCode,
  ArrowRightLeft,
  RefreshCw,
  CircleDot,
  Ruler,
  Calculator,
  Image,
  Sun,
  Signal,
  ListOrdered,
  HeartPulse,
  Brain,
  Terminal,
  ScanLine,
  FileCheck,
  FileText,
};

export function ToolIcon({ name, size = 20 }: { name: string; size?: number }) {
  const Icon = toolIcons[name] ?? Wifi;
  return <Icon size={size} aria-hidden="true" />;
}
