import { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { copyText } from '../utils/clipboard';
import './tools.css';

const BASES = [{ id: 2, name: 'Binary' }, { id: 8, name: 'Octal' }, { id: 10, name: 'Decimal' }, { id: 16, name: 'Hexadecimal' }];
function parse(value: string, base: number): bigint | null { const cleaned = value.trim().replace(/_/g, ''); if (!cleaned) return null; const valid = base === 2 ? /^[01]+$/ : base === 8 ? /^[0-7]+$/ : base === 10 ? /^\d+$/ : /^[0-9a-fA-F]+$/; if (!valid.test(cleaned)) return null; let result = 0n; for (const ch of cleaned) result = result * BigInt(base) + BigInt(parseInt(ch, base)); return result; }
function toBase(n: bigint, base: number): string { if (n === 0n) return '0'; const digits = '0123456789abcdef'; let out = ''; let value = n; while (value > 0n) { out = digits[Number(value % BigInt(base))] + out; value /= BigInt(base); } return out; }

export function BaseConverter() {
  const [value, setValue] = useState('255'); const [base, setBase] = useState(10); const [mode, setMode] = useState<'number' | 'text'>('number'); const [copied, setCopied] = useState(false);
  const n = mode === 'number' ? parse(value, base) : null; const results = n === null ? null : BASES.map(b => ({ ...b, out: toBase(n, b.id) })); const textBytes = mode === 'text' ? Array.from(new TextEncoder().encode(value), b => b.toString(16).padStart(2, '0')).join(' ') : '';
  const copy = async (text: string) => { await copyText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <div className="tool-ui"><div className="tabs" role="tablist"><button className={`tab ${mode === 'number' ? 'active' : ''}`} onClick={() => { setMode('number'); setValue('255'); }} role="tab" aria-selected={mode === 'number'}>Number bases</button><button className={`tab ${mode === 'text' ? 'active' : ''}`} onClick={() => { setMode('text'); setValue('Hello'); }} role="tab" aria-selected={mode === 'text'}>Text → bytes</button></div><div className="field"><label htmlFor="base-in">{mode === 'number' ? 'Value' : 'Text'}</label>{mode === 'number' ? <input id="base-in" className="input" value={value} onChange={e => setValue(e.target.value)} placeholder="255" spellCheck={false} style={{ maxWidth: 260, fontFamily: 'ui-monospace, Consolas, monospace' }} /> : <textarea id="base-in" className="input" value={value} onChange={e => setValue(e.target.value)} placeholder="Hello" spellCheck={false} />}</div>{mode === 'number' && <div className="field"><label>Input base</label><div className="tabs" role="tablist">{BASES.map(b => <button key={b.id} className={`tab ${base === b.id ? 'active' : ''}`} onClick={() => setBase(b.id)} role="tab" aria-selected={base === b.id}>{b.name} ({b.id})</button>)}</div></div>}{mode === 'text' ? <div className="field"><label>UTF-8 bytes as hexadecimal</label><div className="output">{textBytes}</div><button className="btn secondary" onClick={() => copy(textBytes)}>{copied ? <Check size={16} /> : <Copy size={16} />} {copied ? 'Copied' : 'Copy'}</button></div> : results && <div className="field"><table className="result-table"><thead><tr><th>Base</th><th>Value</th><th /></tr></thead><tbody>{results.map(r => <tr key={r.id}><td><span className="badge">{r.name}</span></td><td style={{ fontSize: '1rem' }}>{r.out}</td><td><button className="icon-btn" onClick={() => copy(r.out)} aria-label={`Copy ${r.name}`}>{copied ? <Check size={16} /> : <Copy size={16} />}</button></td></tr>)}</tbody></table><div className="alert info">Uses BigInt, so it handles numbers far beyond JavaScript&apos;s normal safe integer limit.</div></div>}{mode === 'text' && <div className="alert info">Text mode encodes the text as UTF-8 bytes and displays those bytes in hexadecimal. This is different from interpreting a hex string as a number.</div>}</div>;
}
