import { useMemo, useState } from 'react';
import YAML from 'yaml';
import { copyText } from '../utils/clipboard';

const Box = ({ children }: { children: React.ReactNode }) => <div className="tool-ui">{children}</div>;
const Area = (p: React.TextareaHTMLAttributes<HTMLTextAreaElement>) => <textarea {...p} className="tool-textarea" />;
const Copy = ({ value }: { value: string }) => <button className="btn btn-secondary" onClick={() => { void copyText(value); }}>Copy</button>;

export function TextDiff() {
  const [a, setA] = useState(''); const [b, setB] = useState('');
  const rows = useMemo(() => { const aa=a.split('\n'), bb=b.split('\n'); const out: {kind:string;text:string}[]=[]; let i=0,j=0; while(i<aa.length||j<bb.length){ if(aa[i]===bb[j]){out.push({kind:'same',text:`  ${aa[i]??''}`});i++;j++;} else if(j<bb.length && !aa.slice(i+1,i+4).includes(bb[j])){out.push({kind:'add',text:`+ ${bb[j]}`});j++;} else {out.push({kind:'del',text:`- ${aa[i]??''}`});i++;} } return out; },[a,b]);
  return <Box><div className="two-col"><label>Original<Area value={a} onChange={e=>setA(e.target.value)} placeholder="Paste the original text…" /></label><label>Changed<Area value={b} onChange={e=>setB(e.target.value)} placeholder="Paste the changed text…" /></label></div><div className="tool-actions"><Copy value={rows.map(r=>r.text).join('\n')} /><button className="btn btn-secondary" onClick={()=>{setA('');setB('')}}>Clear</button></div><pre className="json-output diff-output">{rows.map((r,n)=><span key={n} className={`diff-${r.kind}`}>{r.text}{'\n'}</span>)}</pre></Box>;
}

export function YamlJson() {
  const [input,setInput]=useState(''); const [mode,setMode]=useState<'yaml'|'json'>('yaml'); const [error,setError]=useState('');
  const output=useMemo(()=>{try{setError(''); if(!input.trim())return ''; return mode==='yaml'?JSON.stringify(YAML.parse(input),null,2):YAML.stringify(JSON.parse(input));}catch(e){setError(e instanceof Error?e.message:'Invalid input');return ''}},[input,mode]);
  return <Box><div className="tabs"><button className={`tab ${mode==='yaml'?'active':''}`} onClick={()=>setMode('yaml')}>YAML → JSON</button><button className={`tab ${mode==='json'?'active':''}`} onClick={()=>setMode('json')}>JSON → YAML</button></div><Area value={input} onChange={e=>setInput(e.target.value)} placeholder={mode==='yaml'?'name: NAB Tools\nfeatures:\n  - private':'{"name":"NAB Tools","private":true'} /><div className="tool-actions">{output&&<Copy value={output}/>}<button className="btn btn-secondary" onClick={()=>setInput('')}>Clear</button></div>{error?<p className="error-text">{error}</p>:output&&<pre className="json-output">{output}</pre>}</Box>;
}

function formatSql(sql:string){return sql.replace(/\s+/g,' ').replace(/\s*,\s*/g,', ').replace(/\b(FROM|WHERE|GROUP BY|ORDER BY|HAVING|LIMIT|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|OUTER JOIN|UNION|SET|VALUES)\b/gi,'\n$1 ').replace(/\b(AND|OR)\b/gi,'\n  $1 ').trim();}
export function SqlFormatter(){const [v,setV]=useState('');const [min,setMin]=useState(false);const out=min?v.replace(/\s+/g,' ').trim():formatSql(v);return <Box><Area value={v} onChange={e=>setV(e.target.value)} placeholder="SELECT id, name FROM users WHERE active = true ORDER BY name;"/><label className="check"><input type="checkbox" checked={min} onChange={e=>setMin(e.target.checked)}/> Minify</label><div className="tool-actions"><Copy value={out}/><button className="btn btn-secondary" onClick={()=>setV('')}>Clear</button></div><pre className="json-output">{out}</pre></Box>}

export function XmlFormatter(){const [v,setV]=useState('');const [min,setMin]=useState(false);const out=min?v.replace(/>\s+</g,'><').trim():v.replace(/>\s*</g,'>\n<').replace(/(<[^/!?][^>]*>)\s*(<)/g,'$1\n$2');return <Box><Area value={v} onChange={e=>setV(e.target.value)} placeholder={'<catalog><item id="1">NAB Tools</item></catalog>'}/><label className="check"><input type="checkbox" checked={min} onChange={e=>setMin(e.target.checked)}/> Minify whitespace</label><div className="tool-actions"><Copy value={out}/></div><pre className="json-output">{out}</pre></Box>}

function hexRgb(hex:string){const h=hex.replace('#','');const x=h.length===3?h.split('').map(c=>c+c).join(''):h;return [0,2,4].map(i=>parseInt(x.slice(i,i+2),16)/255)}
function lum(hex:string){return hexRgb(hex).map(c=>c<=.03928?c/12.92:((c+.055)/1.055)**2.4).reduce((s,c,i)=>s+c*[.2126,.7152,.0722][i],0)}
export function ContrastChecker(){const [fg,setFg]=useState('#ffffff');const [bg,setBg]=useState('#0b0d10');const ratio=(Math.max(lum(fg),lum(bg))+.05)/(Math.min(lum(fg),lum(bg))+.05);return <Box><div className="color-inputs"><label>Text colour<input type="color" value={fg} onChange={e=>setFg(e.target.value)}/><input value={fg} onChange={e=>setFg(e.target.value)} /></label><label>Background<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/><input value={bg} onChange={e=>setBg(e.target.value)} /></label></div><div className="contrast-box" style={{color:fg,background:bg}}>Sample text — WCAG contrast preview<br/><small>{ratio.toFixed(2)}:1</small></div><table className="result-table"><tbody>{[['AA normal',ratio>=4.5],['AA large',ratio>=3],['AAA normal',ratio>=7],['AAA large',ratio>=4.5]].map(([n,ok])=><tr key={String(n)}><td>{n}</td><td>{ok?'Pass':'Fail'}</td></tr>)}</tbody></table></Box>}

export function UrlParser(){const [v,setV]=useState('https://example.com/tools/json-formatter?mode=pretty#top');let data:URL|undefined;try{data=new URL(v)}catch{};const rows=data?[['Protocol',data.protocol],['Host',data.host],['Path',data.pathname],['Query',data.search],['Hash',data.hash],...Array.from(data.searchParams.entries()).map(([k,x])=>[`Param: ${k}`,x])]:[];return <Box><Area value={v} onChange={e=>setV(e.target.value)} /><div className="result-table">{data?rows.map(([k,x])=><div className="url-row" key={k}><strong>{k}</strong><code>{x}</code></div>):<p className="error-text">Enter a complete URL, including https://</p>}</div></Box>}

export function ExifViewer(){const [info,setInfo]=useState<string[]>([]);const read=(file:File)=>{const r=new FileReader();r.onload=()=>{const b=new Uint8Array(r.result as ArrayBuffer);const text=new TextDecoder('latin1').decode(b);const found=[['File name',file.name],['Type',file.type],['Size',`${(file.size/1024).toFixed(1)} KB`],['JPEG EXIF marker',text.includes('Exif\\0\\0')?'Found':'Not found']];setInfo(found.map(x=>`${x[0]}: ${x[1]}`))};r.readAsArrayBuffer(file)};return <Box><label className="file-drop">Choose a local image<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/></label><p className="muted">Files are read locally and never uploaded.</p>{info.length>0&&<pre className="json-output">{info.join('\n')}</pre>}</Box>}

export function SvgOptimizer(){const [v,setV]=useState('');const out=v.replace(/<!--[\s\S]*?-->/g,'').replace(/\s{2,}/g,' ').replace(/>\s+</g,'><').replace(/\s*([=,:])\s*/g,'$1').trim();return <Box><Area value={v} onChange={e=>setV(e.target.value)} placeholder="Paste SVG markup…"/><div className="tool-actions"><Copy value={out}/><span className="muted">{v.length?`${v.length} → ${out.length} bytes`:'Paste SVG to optimize'}</span></div><pre className="json-output">{out}</pre></Box>}

export function UnixPermissions(){const [mode,setMode]=useState('755');const n=parseInt(mode,8)||0;const names=['Owner','Group','Others'];const bits=[6,3,0];const symbolic=bits.map((shift,i)=>{const x=(n>>shift)&7;return `${names[i]}: ${x&4?'r':'-'}${x&2?'w':'-'}${x&1?'x':'-'}`});return <Box><label>Octal permissions<input value={mode} onChange={e=>setMode(e.target.value.replace(/[^0-7]/g,'').slice(-3))}/></label><div className="count-grid"><div className="count-card"><div className="num">{mode||'000'}</div><div className="label">chmod</div></div>{symbolic.map(x=><div className="count-card" key={x}><div className="num">{x.split(': ')[1]}</div><div className="label">{x.split(':')[0]}</div></div>)}</div><p className="muted">Example: 755 = owner can read/write/execute; everyone else can read/execute.</p></Box>}

export function CssFormatter(){const [v,setV]=useState('');const out=v.replace(/\s*{\s*/g,' {\n  ').replace(/;\s*/g,';\n  ').replace(/\s*}\s*/g,'\n}\n').replace(/\n  \n/g,'\n').trim();return <Box><Area value={v} onChange={e=>setV(e.target.value)} placeholder=".button { color: white; background: #123456; }"/><div className="tool-actions"><Copy value={out}/></div><pre className="json-output">{out}</pre></Box>}
