import { useMemo, useState } from 'react';
import { Check, Copy } from 'lucide-react';
import { copyText } from '../utils/clipboard';
import './tools.css';

const printable = (text: string) => [...text].filter(ch => ch === '\n' || ch === '\r' || ch === '\t' || (ch >= ' ' && ch <= '~')).length / Math.max([...text].length, 1);
const base64ToBytes = (value: string) => { const clean = value.trim().replace(/-/g, '+').replace(/_/g, '/'); if (!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(clean)) throw new Error('Invalid Base64'); const binary = atob(clean); return Uint8Array.from(binary, ch => ch.charCodeAt(0)); };
const bytesToHex = (bytes: Uint8Array) => Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('');
const hexToBytes = (value: string) => { const clean = value.trim().replace(/[\s:-]/g, ''); if (!clean || clean.length % 2 || !/^[0-9a-fA-F]+$/.test(clean)) throw new Error('Invalid hexadecimal'); return Uint8Array.from({ length: clean.length / 2 }, (_, i) => parseInt(clean.slice(i * 2, i * 2 + 2), 16)); };
const decodeUtf8 = (bytes: Uint8Array) => new TextDecoder('utf-8', { fatal: true }).decode(bytes);
const encodeUtf8 = (text: string) => new TextEncoder().encode(text);
const escapeUnicode = (text: string) => [...text].map(ch => { const cp = ch.codePointAt(0)!; return cp <= 0xffff ? `\\u${cp.toString(16).padStart(4, '0')}` : `\\u{${cp.toString(16)}}`; }).join('');
const unescapeUnicode = (text: string) => text.replace(/\\u\{([0-9a-fA-F]{1,6})\}|\\u([0-9a-fA-F]{4})/g, (_, point, word) => { const cp = parseInt(point ?? word, 16); return cp <= 0x10ffff ? String.fromCodePoint(cp) : _; });
const encodeEntities = (text: string) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
const decodeEntities = (text: string) => text.replace(/&#x([0-9a-fA-F]+);|&#([0-9]+);|&(amp|lt|gt|quot|apos|nbsp);/g, (whole, hex, dec, named) => { if (hex) { const cp = parseInt(hex, 16); return cp <= 0x10ffff ? String.fromCodePoint(cp) : whole; } if (dec) { const cp = Number(dec); return cp <= 0x10ffff ? String.fromCodePoint(cp) : whole; } return ({ amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: '\u00a0' } as Record<string, string>)[named] ?? whole; });

function CopyButton({ value }: { value: string }) { const [copied, setCopied] = useState(false); return <button className="btn secondary" onClick={async () => { await copyText(value); setCopied(true); setTimeout(() => setCopied(false), 1500); }} disabled={!value}>{copied ? <Check size={16} /> : <Copy size={16} />} {copied ? 'Copied' : 'Copy'}</button>; }
function Editor({ input, setInput, label, placeholder }: { input: string; setInput: (v: string) => void; label: string; placeholder: string }) { return <div className="field"><label>{label}</label><textarea className="input" value={input} onChange={e => setInput(e.target.value)} placeholder={placeholder} spellCheck={false} /></div>; }

export function HexTool() { const [mode, setMode] = useState<'encode' | 'decode'>('encode'); const [input, setInput] = useState('Hello'); const [error, setError] = useState(''); const output = useMemo(() => { try { setError(''); return mode === 'encode' ? bytesToHex(encodeUtf8(input)) : decodeUtf8(hexToBytes(input)); } catch { setError(mode === 'decode' ? 'Invalid hexadecimal. Use an even number of hex digits; spaces, colons, and hyphens are allowed.' : 'Could not encode this text.'); return ''; } }, [input, mode]); return <div className="tool-ui"><div className="tabs" role="tablist"><button className={`tab ${mode === 'encode' ? 'active' : ''}`} onClick={() => setMode('encode')} role="tab" aria-selected={mode === 'encode'}>Text → Hex</button><button className={`tab ${mode === 'decode' ? 'active' : ''}`} onClick={() => setMode('decode')} role="tab" aria-selected={mode === 'decode'}>Hex → Text</button></div><Editor input={input} setInput={setInput} label={mode === 'encode' ? 'Text' : 'Hexadecimal bytes'} placeholder={mode === 'encode' ? 'Hello' : '48 65 6c 6c 6f'} />{error && <div className="alert error">{error}</div>}{output && <div className="field"><label>{mode === 'encode' ? 'Hex output' : 'Decoded UTF-8 text'}</label><div className="output">{output}</div><CopyButton value={output} /></div>}<div className="alert info">Hex represents bytes, not necessarily readable text. A hash or compressed file may be valid hex but will not decode into useful UTF-8.</div></div>; }

export function UnicodeEscapeTool() { const [mode, setMode] = useState<'encode' | 'decode'>('encode'); const [input, setInput] = useState('Café ☕'); const output = mode === 'encode' ? escapeUnicode(input) : unescapeUnicode(input); return <div className="tool-ui"><div className="tabs" role="tablist"><button className={`tab ${mode === 'encode' ? 'active' : ''}`} onClick={() => setMode('encode')} role="tab" aria-selected={mode === 'encode'}>Text → Unicode escapes</button><button className={`tab ${mode === 'decode' ? 'active' : ''}`} onClick={() => setMode('decode')} role="tab" aria-selected={mode === 'decode'}>Escapes → Text</button></div><Editor input={input} setInput={setInput} label={mode === 'encode' ? 'Text' : 'Escaped text'} placeholder={mode === 'encode' ? 'Café ☕' : '\\u0043\\u0061\\u0066\\u00e9'} /><div className="field"><label>{mode === 'encode' ? 'Unicode escape output' : 'Decoded text'}</label><div className="output">{output}</div><CopyButton value={output} /></div><div className="alert info">Uses JavaScript/JSON-style escapes. BMP characters use \\uFFFF; supplementary characters such as emoji use the readable ES6 form {'\\u{1f600}'}.</div></div>; }

export function HtmlEntityTool() { const [mode, setMode] = useState<'encode' | 'decode'>('encode'); const [input, setInput] = useState('<p>Tom & Jerry</p>'); const output = mode === 'encode' ? encodeEntities(input) : decodeEntities(input); return <div className="tool-ui"><div className="tabs" role="tablist"><button className={`tab ${mode === 'encode' ? 'active' : ''}`} onClick={() => setMode('encode')} role="tab" aria-selected={mode === 'encode'}>Text → HTML entities</button><button className={`tab ${mode === 'decode' ? 'active' : ''}`} onClick={() => setMode('decode')} role="tab" aria-selected={mode === 'decode'}>Entities → Text</button></div><Editor input={input} setInput={setInput} label={mode === 'encode' ? 'Text / HTML' : 'HTML entities'} placeholder={mode === 'encode' ? '<p>Tom & Jerry</p>' : '&lt;p&gt;Tom &amp; Jerry&lt;/p&gt;'} /><div className="field"><label>{mode === 'encode' ? 'Encoded output' : 'Decoded text'}</label><div className="output">{output}</div><CopyButton value={output} /></div><div className="alert info">This encodes the five HTML-sensitive characters and decodes common named, decimal, and hexadecimal entities. It does not sanitize HTML or make untrusted markup safe to render.</div></div>; }

type Finding = { name: string; detail: string; decoded?: string };
function inspect(value: string): Finding[] { if (!value.trim()) return []; const findings: Finding[] = []; const trimmed = value.trim(); if (/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(trimmed)) findings.push({ name: 'JWT-shaped', detail: 'Three dot-separated Base64URL segments; structure alone does not verify a signature.' }); try { const bytes = base64ToBytes(trimmed); const text = decodeUtf8(bytes); findings.push({ name: 'Base64 / Base64URL', detail: `${bytes.length} decoded bytes; printable UTF-8 ${(printable(text) * 100).toFixed(0)}%.`, decoded: text }); } catch { /* not Base64 */ } try { const bytes = hexToBytes(trimmed); let text = ''; try { text = decodeUtf8(bytes); } catch { /* binary */ } findings.push({ name: 'Hexadecimal bytes', detail: `${bytes.length} decoded bytes${text ? `; printable UTF-8 ${(printable(text) * 100).toFixed(0)}%` : '; binary or non-UTF-8 data'}.`, decoded: text || undefined }); } catch { /* not hex */ } if (/%[0-9a-fA-F]{2}/.test(trimmed)) { try { findings.push({ name: 'Percent-encoded text', detail: 'Contains valid-looking %XX escapes.', decoded: decodeURIComponent(trimmed) }); } catch { findings.push({ name: 'Malformed percent-encoding', detail: 'Contains % escapes but does not decode as a complete URI component.' }); } } if (/&(?:amp|lt|gt|quot|apos|nbsp);|&#(?:x[0-9a-fA-F]+|[0-9]+);/.test(trimmed)) findings.push({ name: 'HTML entities', detail: 'Contains named or numeric HTML character references.', decoded: decodeEntities(trimmed) }); if (/\\u(?:[0-9a-fA-F]{4}|\{[0-9a-fA-F]{1,6}\})/.test(trimmed)) findings.push({ name: 'Unicode escapes', detail: 'Contains JavaScript-style Unicode escape sequences.', decoded: unescapeUnicode(trimmed) }); if (/^[01]+$/.test(trimmed) && trimmed.length % 8 === 0) findings.push({ name: 'Binary bytes', detail: `${trimmed.length / 8} byte(s) expressed as 8-bit binary groups.` }); return findings; }
export function EncodingInspector() { const [input, setInput] = useState('SGVsbG8='); const findings = useMemo(() => inspect(input), [input]); const [chain, setChain] = useState(''); const apply = (kind: string) => { try { if (kind === 'base64') setChain(decodeUtf8(base64ToBytes(chain || input))); else if (kind === 'hex') setChain(decodeUtf8(hexToBytes(chain || input))); else if (kind === 'url') setChain(decodeURIComponent(chain || input)); else if (kind === 'html') setChain(decodeEntities(chain || input)); else if (kind === 'unicode') setChain(unescapeUnicode(chain || input)); } catch { setChain('Could not decode with that format.'); } }; return <div className="tool-ui"><Editor input={input} setInput={setInput} label="Value to inspect" placeholder="Paste an encoded value…" />{findings.length ? <div className="field"><label>Possible formats</label>{findings.map(f => <div className="alert info" key={f.name}><strong>{f.name}</strong> — {f.detail}{f.decoded !== undefined && <div style={{ marginTop: 6, fontFamily: 'ui-monospace, Consolas, monospace', wordBreak: 'break-word' }}>Preview: {f.decoded.slice(0, 240)}</div>}</div>)}</div> : <div className="alert info">No supported format was detected. Detection is heuristic: valid text can match more than one format.</div>}<div className="field"><label>Explicit decode chain</label><div className="row"><button className="btn secondary" onClick={() => apply('base64')}>Base64</button><button className="btn secondary" onClick={() => apply('hex')}>Hex</button><button className="btn secondary" onClick={() => apply('url')}>URL</button><button className="btn secondary" onClick={() => apply('html')}>HTML</button><button className="btn secondary" onClick={() => apply('unicode')}>Unicode</button></div><div className="output" style={{ marginTop: 10 }}>{chain || 'Choose a decoder; each click applies one explicit step.'}</div>{chain && <CopyButton value={chain} />}</div><div className="alert info">Detection is a best-effort inspection aid, not proof of an encoding. Hashes, IDs, compressed data, and encrypted data can look like encoded text. Everything runs locally in your browser.</div></div>; }

export function ByteBaseTool() { const [input, setInput] = useState('Hello'); const [mode, setMode] = useState<'text' | 'number'>('text'); const result = mode === 'text' ? bytesToHex(encodeUtf8(input)) : (() => { try { const n = BigInt(input.trim()); return `Binary: ${n.toString(2)}\nOctal: ${n.toString(8)}\nDecimal: ${n}\nHexadecimal: ${n.toString(16)}`; } catch { return 'Enter a whole number.'; } })(); return <div className="tool-ui"><div className="tabs" role="tablist"><button className={`tab ${mode === 'text' ? 'active' : ''}`} onClick={() => setMode('text')} role="tab" aria-selected={mode === 'text'}>Text → bytes</button><button className={`tab ${mode === 'number' ? 'active' : ''}`} onClick={() => setMode('number')} role="tab" aria-selected={mode === 'number'}>Number bases</button></div><Editor input={input} setInput={setInput} label={mode === 'text' ? 'Text' : 'Decimal whole number'} placeholder={mode === 'text' ? 'Hello' : '255'} /><div className="field"><label>Output</label><div className="output">{result}</div><CopyButton value={result} /></div><div className="alert info">Text mode shows the UTF-8 bytes as hexadecimal. Number mode is the existing exact BigInt base conversion use case.</div></div>; }
